modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0-only"

[[mods]]
modId="territorycontrolcompat"
version="${file.jarVersion}"
displayName="界域沙盘：模组适配"
logoFile="territorycontrolcompat.png"
authors="ARXYT"
description='''界域沙盘的可选模组适配附属。提供方块与深蓝之树、眼魔、法耶病、真菌感染：孢子等模组的扩散限制与易主清理逻辑，并在安装 CustomNPCs 时提供 CNPC 子阵营映射。需要安装界域沙盘本体。'''

[[dependencies.territorycontrolcompat]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.territorycontrolcompat]]
modId="spore"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.territorycontrolcompat]]
modId="sporesrp"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.territorycontrolcompat]]
modId="customnpcs"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.territorycontrolcompat]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.territorycontrolcompat]]
modId="territorycontrol"
mandatory=true
versionRange="[0.8.1,)"
ordering="AFTER"
side="BOTH"
